services:
  server:
    build:
      context: .
      args:
        - DB_USER=postgres
        - DB_PASSWORD
        - DB_NAME=sitoWow
        - DB_HOST=db
        - PORT=4000
        - ADMIN_NAME
        - ADMIN_PASSWORD
    image: jelly/sito-wow
    container_name: sitoWow
    restart: unless-stopped
    volumes:
      - ./storage:/data/storage
      - ./tls:/app/tls
      - ./ui/static:/app/static # Not really needed
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: sitoWow-db
    image: postgres:16
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=sitoWow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "sitoWow"]
      interval: 3s
      timeout: 30s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: sitoWow-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  pgdata:
